### ISSUE TITLE
Create a basic class which can have a puzzle loaded into it.

### ISSUE THREAD

**Issue by Ross-Alexandra** [ross3834/SudokuPlayer#1]
### Summary
This class should represent a Sudoku puzzle. In other words, there should be a way to load a puzzle, view a puzzle, alter a puzzle, change rows, etc. In essence, a puzzle should be loadable, and solvable by a human writing code.

### Acceptance Criteria
 * A class is created that represents a basic Sudoku puzzle.
  * A puzzle (represented by a 2D list) can be loaded into the puzzle.
  * A cell can be directly set.
  * Each row, columns and box are returned by a function call
  * A "validate" attribute should exist, allowing the puzzle to raise exceptions when an invalid move is made.

**Comment by Ross-Alexandra-Review** [comment]
With GH-1 merged, all the acceptance criteria have been met.
